# Generated by Django 5.0.7 on 2024-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archif',
            field=models.BooleanField(default=False),
        ),
    ]
